import {useOwnedClient, useAsyncAction, useServiceCommands} from '../src/react/index.js'

function publicTypes() {
    const owner = useOwnedClient({key: 'session', create: async () => ({
        ready: async () => {}, close() {}, commands: {value: 1},
    })})
    const value: number | undefined = owner.client?.commands.value
    // @ts-expect-error only exclusively disposable resources may be owned
    useOwnedClient({key: 0, create: () => ({ready: Promise.resolve()})})
    const action = useAsyncAction()
    const result: Promise<number> = action.run(async () => 42)
    const commands = useServiceCommands({
        save: async (id: string, input: {title: string}) => ({id, length: input.title.length}),
        remove: (id: string, input: {index: number}) => input.index > 0,
        ping: (id: string) => id,
    })
    const saved: Promise<{id: string; length: number}> = commands.run('save', {title: 'one'})
    const removed: Promise<boolean> = commands.run('remove', {index: 1})
    const ping: Promise<string> = commands.run('ping')
    // @ts-expect-error unknown command
    commands.run('missing', {})
    // @ts-expect-error input belongs to a different command; must not widen command name
    commands.run('save', {index: 1})
    // @ts-expect-error wrong scalar input
    commands.run('remove', {index: 'one'})
    // @ts-expect-error missing required input
    commands.run('save')
    // @ts-expect-error request ID is generated by the binding, not passed by UI
    commands.run('ping', 'id')
    // @ts-expect-error command maps must take string request ids
    useServiceCommands({bad: (id: number) => id})
    return {value, result, saved, removed, ping}
}
