/** Compatibility barrel. Generated by scripts/generate-root-barrel.mjs.
 * New code imports canonical subpaths; ./native is intentionally separate.
 * Per-specifier JSDoc preserves IDE deprecation without deprecating canonical bindings.
 */

export {
    /** @deprecated Import from 'wenay-react2/core' instead. */
    tokens,
    /** @deprecated Import from 'wenay-react2/core' instead. */
    tokensVar,
    /** @deprecated Import from 'wenay-react2/core' instead. */
    createCallbackHub,
    /** @deprecated Import from 'wenay-react2/core' instead. */
    movedOrderWithFixed,
    /** @deprecated Import from 'wenay-react2/core' instead. */
    pinFixedOrder,
    /** @deprecated Import from 'wenay-react2/core' instead. */
    ObservableMap,
    /** @deprecated Import from 'wenay-react2/core' instead. */
    structEqual,
} from './core/index.js';

export type {
    /** @deprecated Import from 'wenay-react2/core' instead. */
    Tokens,
    /** @deprecated Import from 'wenay-react2/core' instead. */
    TokensVar,
    /** @deprecated Import from 'wenay-react2/core' instead. */
    FixedOrderDescriptor,
    /** @deprecated Import from 'wenay-react2/core' instead. */
    MapChangeListener,
} from './core/index.js';

export {
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    restoreDates,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    createCacheMap,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    createCacheMapWithStorage,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    browserCacheStorage,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    localStorageCache,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    memoryCache,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    memoryMaps,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    memoryCommit,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    memoryGet,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    memoryGetById,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    memoryGetOrCreate,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    memoryMarkDirty,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    memorySet,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    memoryUpdate,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    buttonStatusMap,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    floatingWindowMap,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    mapResiReact,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    mapRightMenu,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    createPersistedController,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    createSearchHistory,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    useCacheMapPersistence,
} from './persist/index.js';

export type {
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    CacheMap,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    CacheStorage,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    DirtyListener,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    ButtonSavedState,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    MenuRightPosition,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    MenuRightSavedState,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    MenuRightVerticalPosition,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    ResizableSavedSize,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    FloatingWindowCloseReason,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    FloatingWindowMode,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    FloatingWindowPosition,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    FloatingWindowSavedGeometry,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    FloatingWindowSize,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    FloatingWindowSnapRegion,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    PersistedController,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    PersistedControllerOptions,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    SearchHistoryApi,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    SearchHistoryState,
    /** @deprecated Import from 'wenay-react2/persist' instead. */
    CacheMapPersistence,
} from './persist/index.js';

export {
    /** @deprecated Import from 'wenay-react2/react' instead. */
    __observerStateForTests,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    createUpdateApi,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    renderBy,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    renderByLast,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    renderByRevers,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    updateBy,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useUpdateBy,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useUpdateByApi,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useOwnedClient,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useAsyncAction,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useServiceCommands,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    AsyncActionBusyError,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    AsyncActionUnavailableError,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useOutside,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useOutsideApi,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useOutsideRef,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    keyboard,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    keyboardState,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useKeyboard,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useDraggable,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useDraggableApi,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useReorder,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useReorderBoard,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useListenArgs,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useListenEffect,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useListenValue,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreChangedPaths,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreEach,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreKeys,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreMirror,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreNode,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreSelect,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useReplayFrame,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useReplayHistory,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useReplayRouteSubscribe,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useReplaySubscribe,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreLazyLineMirror,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreLazyLineSync,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreReplayEach,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreReplayMirror,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreReplayRouteMirror,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreReplayRouteSync,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useStoreReplaySync,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useRouteState,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useAiRunClient,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useClientStore,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useFileJobClient,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useContractSlot,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    CResizeObserver,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useElementSize,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    useResizeObserver,
} from './react/index.js';

export type {
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UpdateApi,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UpdateCallback,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    OwnedClient,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseOwnedClientOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    OwnedClientController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    AsyncActionController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ServiceCommandMap,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ServiceCommandsController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ServiceCommandCall,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseOutsideApi,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseOutsideOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    KeyboardApi,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    Position,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseDraggableApi,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    DraggableInputMode,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    DraggableKeyboardOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    DraggableHandleProps,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseDraggableOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseDraggableReturn,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReorderItem,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReorderOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReorderOverlay,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReorderHandleProps,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReorderAutoScrollOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    BoardColumn,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    BoardPosition,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReorderBoardOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ListenLike,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    RemoteStoreLike,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreChange,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreChangedPathsController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreDrain,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreEachCtx,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreKeysController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreMask,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreMirrorController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreNode,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreNodeController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StorePick,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreSelection,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreSelectionController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreSubOpts,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreSyncOpts,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseStoreEachOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseStoreMirrorOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseStoreNodeOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseStoreSelectOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReplayFrameController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReplayHistoryController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReplayHistoryLike,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReplayRouteController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReplayRouteEvent,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReplayRouteSwitchOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ReplaySubscribeController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreLazyLineMirrorController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreLazyLineSyncController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreReplayMirrorController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreReplayRouteMirrorController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreReplayRouteSyncController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreReplaySyncController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseReplayFrameOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseReplayHistoryOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseReplayRouteSubscribeOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseReplaySubscribeOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseStoreLazyLineSyncOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseStoreReplayEachOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseStoreReplayRouteSyncOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    UseStoreReplaySyncOptions,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    RouteLogEntry,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    AiRunClientController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ClientStoreController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    FileJobClientController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    StoreBackedClient,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ContractSlotController,
    /** @deprecated Import from 'wenay-react2/react' instead. */
    ObserveID,
} from './react/index.js';

export {
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridStyleDefault,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    StyleCSSHeadGrid,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    StyleCSSHeadGridEdit,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    StyleGridDefault,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    AgGridTable,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    buildAgTheme,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    colDefCentered,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    colDefWrap,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    createColumnBuffer,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    createGridBuffer,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    defaultAgGridModules,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ensureAgGridModules,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    numericComparator,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    useAgGrid,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    useAgGridTheme,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    createColumnState,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnsMenu,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    MenuStrip,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnDots,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    CardList,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    createColumnGrid,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    useColumnGrid,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    appendGridChromeMenuItem,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    createGridChrome,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    selectGridChromeContextRow,
} from './grid/index.js';

export type {
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    AgGridClassRule,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    AgGridController,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    AgGridTableProps,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    BuildAgThemeOptions,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    BufferTable,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    CleanArgs,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnApplyContext,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnAttach,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnBuffer,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    CreateGridBufferOptions,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GetId,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridApiLike,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridBufferCore,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridBufferMode,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridTransaction,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    NumberPair,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    PushOptions,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    RowId,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ThemeMode,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    UpdateArgs,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    UseAgGridOptions,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnMeta,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnsConfig,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnsSort,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnStateController,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    MenuStripItem,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridCardsProps,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridChromeProps,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridColumn,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridColumnDef,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridController,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridControls,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridDotsProps,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridMenuProps,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridOptions,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridTableProps,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridToolbar,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridToolbarBarProps,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridToolbarOptions,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridToolbarSettingsProps,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridViewMode,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    ColumnGridViewProps,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridChromeCellContext,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridChromeCommand,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridChromeCommandContext,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridChromeCommandGroup,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridChromeContextMenu,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridChromeController,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridChromeCopy,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridChromeGroup,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridChromeOptions,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridChromeProps,
    /** @deprecated Import from 'wenay-react2/grid' instead. */
    GridChromeRowNode,
} from './grid/index.js';

export {
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    FloatingWindow,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    FloatingWindowBase,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    WindowPortal,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    useFloatingWindowController,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    useWindowPortalContainer,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    DragBox,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    FloatingWindowTaskbar,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    cascadeWindowPosition,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    useFloatingDesktopWindow,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    useFloatingWindowManager,
} from './windows/index.js';

export type {
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    DragBoxProps,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    FloatingWindowController,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    FloatingWindowControllerOptions,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    FloatingWindowProps,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    FloatingWindowUpdate,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    FloatingDesktopEntry,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    FloatingDesktopStack,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    FloatingDesktopWindow,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    FloatingWindowManager,
    /** @deprecated Import from 'wenay-react2/windows' instead. */
    FloatingWindowTaskbarProps,
} from './windows/index.js';

export {
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    createLogsController,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    createLogsControllerState,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    getSettingLogs,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MessageEventLogCard,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MessageEventLogs,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MessageEventLogsView,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    PageLogs,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    getLogsApi,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    logsApi,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    useLogsPageTable,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    useMessageEventLogsController,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MiniLogs,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MiniLogsTable,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MiniLogsView,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    miniLogsColumnDefs,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    miniLogsDefaultColDef,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    useMiniLogsTable,
} from './logs/index.js';

export type {
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    CreateLogsControllerOptions,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogEntry,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogInput,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogsApiOptions,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogsChange,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogsController,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogsControllerEvents,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogsControllerState,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogsFullState,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogsMiniState,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogsSettings,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogsSettingsDefinition,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogsSettingsState,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogsPageTableController,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    LogsViewState,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MessageEventLogsController,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MessageEventLogsItem,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MessageEventLogsViewProps,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    UseMessageEventLogsControllerOptions,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MiniLogsController,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MiniLogsTableController,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MiniLogsTableProps,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    MiniLogsViewProps,
    /** @deprecated Import from 'wenay-react2/logs' instead. */
    UseMiniLogsTableOptions,
} from './logs/index.js';

export {
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    useMediaSource,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    usePeer,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    usePeerCalls,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    usePeerPresence,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCall,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    useVideoCallController,
} from './communication/index.js';

export type {
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    UseMediaSourceController,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    PeerPresence,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    UseVideoCallControllerOptions,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallAssistant,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallController,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallFocusMode,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallLayout,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallMediaState,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallMeeting,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallMessage,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallPanel,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallParticipant,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallPhase,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallPoll,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallProps,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallRecording,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallRecordingState,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallRoom,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallScreenState,
    /** @deprecated Import from 'wenay-react2/communication' instead. */
    VideoCallTone,
} from './communication/index.js';

export {
    /** @deprecated Import from 'wenay-react2/params' instead. */
    ParamsEditor,
    /** @deprecated Import from 'wenay-react2/params' instead. */
    useParamsEditorController,
    /** @deprecated Import from 'wenay-react2/params' instead. */
    ParamLabelContent,
    /** @deprecated Import from 'wenay-react2/params' instead. */
    ParamRow,
    /** @deprecated Import from 'wenay-react2/params' instead. */
    ParamToggleLabel,
    /** @deprecated Import from 'wenay-react2/params' instead. */
    ParamsArrayEdit,
    /** @deprecated Import from 'wenay-react2/params' instead. */
    ParamsEdit,
    /** @deprecated Import from 'wenay-react2/params' instead. */
    setAutoStepForElement,
} from './params/index.js';

export type {
    /** @deprecated Import from 'wenay-react2/params' instead. */
    ParamsEditorController,
    /** @deprecated Import from 'wenay-react2/params' instead. */
    ParamsEditorControllerOptions,
} from './params/index.js';

export {
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    ModalProvider,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    useModal,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    confirmModal,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    createModalElementStore,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    createModalRenderStore,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    inputModal,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    LeftModal,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    getApiLeftMenu,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    FileInputModal,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    FileInputPanel,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    FreeModal,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    TextInputModal,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    TextInputPanel,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    useFileInputPanel,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    useTextInputPanel,
} from './modal/index.js';

export type {
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    ModalApi,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    ModalController,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    ModalProviderProps,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    FileInputPanelProps,
    /** @deprecated Import from 'wenay-react2/modal' instead. */
    TextInputPanelProps,
} from './modal/index.js';

export {
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    Menu,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuProgress,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuItemElement,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    contextMenu,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    createContextMenu,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    DropdownMenu,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    createRightMenuController,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    useRightMenuController,
} from './menu/index.js';

export type {
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuActionEvent,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuActionEventType,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuActionHandler,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuItem,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuItemStrict,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    ContextMenuActionCounters,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    ContextMenuAnchor,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    ContextMenuGesture,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    ContextMenuLayerProps,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    ContextMenuPoint,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    ContextMenuProvided,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    ContextMenuState,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    ContextMenuStats,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    ContextMenuStatsSnapshot,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    DropdownMenuProps,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuElement,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuRightClassNames,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuRightRenderProps,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuRightStyles,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuRightTrigger,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    MenuRightTriggerState,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    RightMenuController,
    /** @deprecated Import from 'wenay-react2/menu' instead. */
    UseRightMenuControllerOptions,
} from './menu/index.js';

export {
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    Sparkline,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    createDataModel,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    createDataSet,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    createPanelManager,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    createRenderer,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    createInteraction,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    createChartEngine,
} from './chart/index.js';

export type {
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    SparklineProps,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    SparklineSeries,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    SparklineTheme,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    ChartType,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    CreateDataSetParams,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    DataModel,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    DataPoint,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    DataSet,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    DataSetStyle,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    MinMaxChunk,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    Panel,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    PanelConfig,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    PanelManager,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    Renderer,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    Transform,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    Interaction,
    /** @deprecated Import from 'wenay-react2/chart' instead. */
    ChartEngine,
} from './chart/index.js';

export {
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    AbsoluteButton,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    Button,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    HoverButton,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    OutsideButton,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    MiniButton,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    PopupButton,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    OutsideClickArea,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    Overlay,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    removeResizeableElement,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    setResizeableElement,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    FResizableReact,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    createUiSlot,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    createToolbar,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    getToolbarDensities,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    registerToolbarDensity,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    toolbarItemIcon,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    SettingsDialog,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    getSettingsSections,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    registerSettingsSection,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    useSettingsDialogController,
} from './ui/index.js';

export type {
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    OverlayProps,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    ToolbarConfig,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    ToolbarDensity,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    ToolbarItem,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    ToolbarSourceMode,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    UiListConfig,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    UiListSource,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    SettingsDialogController,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    SettingsDialogProps,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    SettingsDialogTreeToolState,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    SettingsSearchSource,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    SettingsSearchTerm,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    SettingsSection,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    SettingsTree,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    SettingsTreeFilter,
    /** @deprecated Import from 'wenay-react2/ui' instead. */
    SettingsTreeNode,
} from './ui/index.js';
